In [1]:
import numpy


In [5]:
# Example
Myarray = numpy.array([[1, 2, 4, 5, 6]])
print(Myarray,type(Myarray))

[[1 2 4 5 6]] <class 'numpy.ndarray'>


# Checking Numpy version

In [6]:
print (numpy.__version__)

2.5.2


# Creating Arrays

-> The array object in NumPy is called ndarray

In [ ]:
#Convert list to array
import numpy as np 


arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [11]:
#Convert Dictionary to array

dict = {'a': 1, 'b': 2, 'c': 3}
arr = np.array(list(dict.values()))
arr

array([1, 2, 3])

# 0 Dimentional Array

In [12]:
arr = np.array(100)
print(arr)

100


In [14]:
oneD = np.array([1, 2, 3, 4, 5])
print(oneD)

#attributes of array

print(oneD.ndim) #Dimension of the array
print(oneD.shape) #shape of the array in row and column     
print(oneD.size) #Size
print(oneD.itemsize) #size in bytes
print(oneD.dtype) # Data type of array elements


[1 2 3 4 5]
1
(5,)
5
8
int64


# Creating 2-dimensional ndarray

In [15]:
twoD = np.array([[1,2,3],[4,5,6]])
print(twoD)

elem = [[1,2,3,4],[9,8,7,6]]
print(twoD.ndim)  # or other attributes like .shape, .size, .dtype, etc.
print(twoD.shape)
print(twoD.size)
print(twoD.itemsize)
print(twoD.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
8
int64


# Creating 3-Dimensional ndarray

In [17]:
threeD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(threeD)

elem = [[1,2,3,4],[9,8,7,6],[4,5,6,7]]
print(threeD.ndim)  # or other attributes like .shape, .size, .dtype, etc.
print(threeD.shape)
print(threeD.size)
print(threeD.itemsize)
print(threeD.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
8
int64


# Functions

In [20]:
# Creating array with all elements as zero

import numpy as np
x = np.zeros((2,2), dtype=int)
x

array([[0, 0],
       [0, 0]])

In [4]:
import numpy

numpy.ones((2, 2), dtype=int)


array([[1, 1],
       [1, 1]])

In [9]:
numpy.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [36]:
numpy.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [45]:
import numpy as numpy
import sys

List1 = [1, 2, 3, 4, 5] 
print (sys.getsizeof(List1)) # size of list in bytes

arr = numpy.array(List1)
print(arr.size*arr.itemsize) # size of array in bytes
print(arr.nbytes) 


104
40
40


In [56]:
import numpy as np
import time

l1 = range(1,100000)
l2 = range(1,100000)
A1 = np.array(l1)
A2 = np.array(l2)

#to be performed on list

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]  

print((time.time()-start)*1000) # time in milliseconds

#operation to be performed on numpy array

start1 = time.time()
result1 = A1 + A2
print((time.time()-start1)*1000) # time in milliseconds

36.783456802368164
0.5993843078613281


# Choice() Method

-> Generate a random sample from a given 1-D array. 
* It is used to create a random sample from a given 1-D array.
* The random sample is generated based on the specified size and probability distribution.

In [5]:
import numpy as np
rng= np.random.default_rng()
x=np.random.choice([1,2,3,4,5,6,7,8], size=10)
y=np.random.choice([1,2,3,4,5,6,7,8], size=(2,2))
z = rng.choice([1,2,3,4,5,6,7,8])
print(x)
print(y)
print(z)



[1 1 4 3 8 1 2 7 6 8]
[[6 5]
 [7 7]]
2


In [3]:
import numpy as np
y=np.array([[12,13,14],[2,4,6]])
print(y[0,2])
print(y[0][2])

14
14


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
b = np.array([[6,7,8,9,10],[1,2,3,4,5]])
print(a[4])                                            # Accessing element at index 4 in array a
print(b[0,4])                                          # Accessing element at row 0, column 4 in array b
print(b[1][4])                                         # Accessing element at row 1, column 4 in array b
print(b[1:])                                           # Slicing rows from index 1 to the end
print(b[:,2])                                          # Slicing columns from index 2 to the end
print(b[0:2,1:4])                                      # Slicing rows from index 0 to 1 and columns from index 1 to 3
print(b[-1])                                           # Accessing the last row
print(b[-1:,-1:])                                      # Slicing the last row and last column


5
10
5
[[1 2 3 4 5]]
[8 3]
[[7 8 9]
 [2 3 4]]
[1 2 3 4 5]
[[5]]


In [8]:
import numpy as np
a=np.random.choice([1,2,3,4,5,6,7,8], size=10)

In [13]:
y = np.array([[12,13,14],[2,4,6],[7,8,9],[10,11,12]])

y[0:2,1:]  # Slicing rows from index 0 to 1 with a step of 1
y[:,1:]

array([[13, 14],
       [ 4,  6],
       [ 8,  9],
       [11, 12]])

In [ ]:
import numpy as np
arr= np.array([1,2,3,4])
s = arr[1:3]                                 # Create a slice of the array
s[0] = 100                                   # Modify the first element of the slice
print(arr)                                   # Print the original array
print(s)                                     # Print the slice
print(s.base)                                # Print the base array of the slice

[  1 100   3   4]
[100   3]
[  1 100   3   4]


# OPERATOR

In [9]:
import numpy as np

y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y[y%2==0]  # This will return a boolean array indicating which elements are even

array([2, 4, 6, 8])

In [ ]:
# * Slicing with boolean indexing allows you to select elements from an array based on a condition. In this case, `y[y%2==0]` will return all the even numbers from the array `y`

# Fancy Indexing 

* fancy indexing is like the simple indexing we've already seen, but we pass arrays of indices in place of single scalars

In [ ]:
import numpy as np 
arr = np.random.randint(2,100, size=(10,10))
xy = np.random.rand(10,10)
print(arr)
print(xy)
print([[1,3,6],[2,7,9]])

[[14 66 97 71 13 18 34 31  9 20]
 [95 54 78 22 71 78 91 38 53  2]
 [96 65 75  5 45 33 86 23 83 69]
 [30 17 75 54 61 66 63 91 45 23]
 [91 96 55 14 54 85 39 35  7 78]
 [91 23 92 53 51 70 93 73 19 30]
 [50 38 80 70 20 11 97 96 89 10]
 [46 88 71 23 86 45 54 25 32 20]
 [11 74  7 83 91 62 65 74 82 87]
 [67 28 66 88 42 88  6 52 87 38]]
[[0.25591815 0.72628778 0.3798152  0.8965347  0.54733479 0.73275547
  0.97380633 0.14566394 0.43321066 0.29974749]
 [0.8964667  0.16897493 0.49099162 0.40604259 0.61485849 0.0321059
  0.71586395 0.83065662 0.60835847 0.782401  ]
 [0.14153961 0.83044596 0.14983636 0.5743409  0.35773364 0.99297367
  0.05906685 0.42090696 0.15158054 0.10619843]
 [0.73637781 0.52396391 0.39071954 0.64744018 0.71567628 0.19737011
  0.93407825 0.56240905 0.04733266 0.7131152 ]
 [0.5782373  0.5683113  0.12902725 0.58603402 0.76868243 0.19451231
  0.84007647 0.52414425 0.26756449 0.87943646]
 [0.74986304 0.84238365 0.76598368 0.81237178 0.10211202 0.23943827
  0.65235622 0.45919541 0.5

array([1, 4, 3, 8, 1, 2])

In [18]:
arr[:,[1,3,5]]

array([[66, 71, 18],
       [54, 22, 78],
       [65,  5, 33],
       [17, 54, 66],
       [96, 14, 85],
       [23, 53, 70],
       [38, 70, 11],
       [88, 23, 45],
       [74, 83, 62],
       [28, 88, 88]], dtype=int32)

In [17]:
arr[1:7,]

array([[95, 54, 78, 22, 71, 78, 91, 38, 53,  2],
       [96, 65, 75,  5, 45, 33, 86, 23, 83, 69],
       [30, 17, 75, 54, 61, 66, 63, 91, 45, 23],
       [91, 96, 55, 14, 54, 85, 39, 35,  7, 78],
       [91, 23, 92, 53, 51, 70, 93, 73, 19, 30],
       [50, 38, 80, 70, 20, 11, 97, 96, 89, 10]], dtype=int32)

In [1]:
n = np.arange(1,13)
print(n)
x= n.reshape((3,4))
print(x)
print(x)


KeyboardInterrupt



In [ ]:
n = np.arange