# Check it returns a Copy or View ?

In [4]:
import numpy as np

n = np.arange(1, 14)
n[5] = 20
print(n)
id(n)

[ 1  2  3  4  5 20  7  8  9 10 11 12 13]


1799577783152

In [5]:
import numpy as np
y = np.reshape(n, (1, 13)).base
print(y)
id(y)

[ 1  2  3  4  5 20  7  8  9 10 11 12 13]


1799577783152

In [6]:
arr = np.array([1, 2, 3, 4, 5])
x=arr.view()
y = arr.copy()
arr[0] = 42

print(arr)
id(arr)

[42  2  3  4  5]


1799577783056

In [7]:
print(x)
print(id(x))
print(x.base)


[42  2  3  4  5]
1799577782768
[42  2  3  4  5]


In [8]:
print(y)
print(id(y))
print(y.base)

[1 2 3 4 5]
1799577780944
None


# Check if array owns its data

As mentioned above, copies owns the data and views does not own the data. but how can we check this?


# Flattening of Array

In [10]:
x = np.random.randint(10,size=(2,3))
print(x)
x.reshape(-1)

[[0 2 0]
 [6 6 7]]


array([0, 2, 0, 6, 6, 7], dtype=int32)

# Transposing Array

In [12]:
x = np.arange(1, 10).reshape(3, 3)
print(x)
x.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Rotation of array

* Syntax -
  numpy.rot90(m,k=1,axes=(0,1))
  * m     Array of two or more dimensions
  * k     Number of times the array is rotated by 90 degrees
  * axes  The array is rotated in the plane defined by the axes 
  

In [ ]:
m = np.array([[1,2],[3,4],[5,6]])



In [16]:
import numpy as np

m = np.array([[1, 2],[3, 4],[5, 6]])

result = np.rot90(m, k=4, axes=(0, 1))
print(result)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
m = np.rot90(m, k=4)
print(m)

[[1 2]
 [3 4]
 [5 6]]


# Joining of array 
