In [1]:
import numpy


In [5]:
# Example
Myarray = numpy.array([[1, 2, 4, 5, 6]])
print(Myarray,type(Myarray))

[[1 2 4 5 6]] <class 'numpy.ndarray'>


# Checking Numpy version

In [6]:
print (numpy.__version__)

2.5.2


# Creating Arrays

-> The array object in NumPy is called ndarray

In [9]:
#Convert list to array
import numpy as np


arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])

In [11]:
#Convert Dictionary to array

dict = {'a': 1, 'b': 2, 'c': 3}
arr = np.array(list(dict.values()))
arr

array([1, 2, 3])

# 0 Dimentional Array

In [12]:
arr = np.array(100)
print(arr)

100


In [14]:
oneD = np.array([1, 2, 3, 4, 5])
print(oneD)

#attributes of array

print(oneD.ndim) #Dimension of the array
print(oneD.shape) #shape of the array in row and column     
print(oneD.size) #Size
print(oneD.itemsize) #size in bytes
print(oneD.dtype) # Data type of array elements


[1 2 3 4 5]
1
(5,)
5
8
int64


# Creating 2-dimensional ndarray

In [15]:
twoD = np.array([[1,2,3],[4,5,6]])
print(twoD)

elem = [[1,2,3,4],[9,8,7,6]]
print(twoD.ndim)  # or other attributes like .shape, .size, .dtype, etc.
print(twoD.shape)
print(twoD.size)
print(twoD.itemsize)
print(twoD.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
8
int64


# Creating 3-Dimensional ndarray

In [17]:
threeD = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(threeD)

elem = [[1,2,3,4],[9,8,7,6],[4,5,6,7]]
print(threeD.ndim)  # or other attributes like .shape, .size, .dtype, etc.
print(threeD.shape)
print(threeD.size)
print(threeD.itemsize)
print(threeD.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
8
int64


# Functions

In [20]:
# Creating array with all elements as zero

import numpy as np
x = np.zeros((2,2), dtype=int)
x

array([[0, 0],
       [0, 0]])

In [4]:
import numpy

numpy.ones((2, 2), dtype=int)


array([[1, 1],
       [1, 1]])

In [9]:
numpy.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [36]:
numpy.linspace(1, 100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [40]:
import numpy as numpy
import sys

List1 = [1, 2, 3, 4, 5] 
print (sys.getsizeof(List1)) # size of list in bytes

arr = numpy.array(List1)
print(arr.size*arr.itemsize) # size of array in bytes
print(arr.nbytes) 


104
40
40
